# Generated by Django 4.0.3 on 2022-03-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
        ('Driver', '0002_detailsmodel_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('fromplace', models.CharField(max_length=100)),
                ('toplace', models.CharField(max_length=100)),
                ('totalkm', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customername', models.CharField(max_length=100)),
                ('customerphone', models.CharField(max_length=100)),
                ('transfercharge', models.CharField(max_length=100)),
                ('extracharge', models.CharField(max_length=100)),
                ('labourcharge', models.CharField(max_length=100)),
                ('jobrefered', models.CharField(default='Admin', max_length=100)),
                ('assigneddriver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Driver.detailsmodel')),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Item.itemmodel')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Item.itemtypemodel')),
                ('jobstatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='JobDetails.statusmodel')),
            ],
        ),
    ]
