# Generated by Django 4.0.3 on 2022-03-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0002_jobmodels_drivercommision_jobmodels_referercommision'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodels',
            name='Total',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
