# Generated by Django 4.0.3 on 2022-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0003_jobmodels_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodels',
            name='jobrefered',
            field=models.CharField(max_length=100),
        ),
    ]
