# Generated by Django 4.0.3 on 2022-03-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_detailsmodel_drivercommision'),
        ('JobDetails', '0005_alter_jobmodels_assigneddriver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodels',
            name='jobrefered',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.DO_NOTHING, to='Driver.detailsmodel'),
        ),
    ]
