# Generated by Django 4.0.3 on 2022-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0007_alter_jobmodels_jobrefered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodels',
            name='jobstatus',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='StatusModel',
        ),
    ]
