# Generated by Django 4.0.3 on 2022-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='vehicle_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
