# Generated by Django 4.0.3 on 2022-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_detailsmodel_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='referedcommision',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
