# Generated by Django 4.0.3 on 2022-03-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_detailsmodel_referedcommision'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='drivercommision',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
