# Generated by Django 4.0.3 on 2022-03-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='ChargesModel',
        ),
    ]
